### ISSUE TITLE
Fired clay bucket doesn't have doesn't have a recipe

### ISSUE THREAD

**Issue by Nincodedo** [UndeadZeratul/ThereWillBeBlood#161]
From Ep 4 of your LP

**Comment by Roshag** [comment]
Open file "TWBB BetterBeginnings Tweaks.zs" is "scripts" folder, after line "var clayBucket         = <IguanaTweaksTConstruct:clayBucketFired>;" add line "var clayBucketUnfired         = <IguanaTweaksTConstruct:clayBucketUnfired>;"; in the end of file add line "Kiln.addRecipe(clayBucket, clayBucketUnfired, 0.35);"

**Comment by UndeadZeratul** [comment]
Looks like I forgot to tie a recent commit to this issue... whoops.

Either way, [I've already got that covered](https://github.com/UndeadZeratul/ThereWillBeBlood/commit/302158cf73e9f72854c42d9e307b08b5d4d5abac#diff-182fd2ef84c8935a97e06efc23b3f65cR84) in the hotfix branch.

Sadly I've actually been trying to focus more on TWBB's successor pack, so it's stuck in a hotfix branch for now.  However, feel free to download the repository at that commit and build the pack yourself if you'd like.

I'm going to close this since it's basically done, just not merged into master.
